/*
Auto-generated by 1-python/find_col_from_val.py
Seed template: 2-sql/find-ColumnName-containing-target-value.sql
Target table: [PrismaUCamInterface].[prisma].[ProcessParameters]
Search value: 15
Row filter: 1 = 1
Excluded columns: none
*/
SET NOCOUNT ON;

DECLARE @SearchValue NVARCHAR(200) = N'15';

IF OBJECT_ID('tempdb..#Cols') IS NOT NULL DROP TABLE #Cols;
CREATE TABLE #Cols (ColumnName SYSNAME NOT NULL);

IF OBJECT_ID('tempdb..#Hits') IS NOT NULL DROP TABLE #Hits;
CREATE TABLE #Hits (
    ColumnName SYSNAME NOT NULL,
    MatchCount INT     NOT NULL
);

IF OBJECT_ID('tempdb..#Samples') IS NOT NULL DROP TABLE #Samples;

DECLARE @RowFilter NVARCHAR(MAX) = N'1 = 1';
DECLARE @FullTable NVARCHAR(512) = N'[PrismaUCamInterface].[prisma].[ProcessParameters]';

SELECT TOP (0)
    CAST(NULL AS SYSNAME) AS ColumnName,
    t.*
INTO #Samples
FROM [PrismaUCamInterface].[prisma].[ProcessParameters] AS t;
INSERT INTO #Cols (ColumnName)
SELECT c.name
FROM   [PrismaUCamInterface].sys.tables  AS t
JOIN   [PrismaUCamInterface].sys.schemas AS s  ON s.schema_id = t.schema_id
JOIN   [PrismaUCamInterface].sys.columns AS c  ON c.object_id = t.object_id
JOIN   [PrismaUCamInterface].sys.types   AS ty ON ty.user_type_id = c.user_type_id
WHERE  s.name = N'prisma'
  AND  t.name = N'ProcessParameters'
  AND  ty.name IN (N'char', N'nchar', N'varchar', N'nvarchar');
    DECLARE @Col SYSNAME;
    DECLARE @sql NVARCHAR(MAX);

    DECLARE col_cur CURSOR LOCAL FAST_FORWARD FOR
        SELECT ColumnName FROM #Cols;

    OPEN col_cur;
    FETCH NEXT FROM col_cur INTO @Col;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @sql = N'
IF EXISTS (
    SELECT 1
    FROM ' + @FullTable + N'
            WHERE ' + QUOTENAME(@Col) + N' = @p
      AND ' + @RowFilter + N'
)
BEGIN
 INSERT INTO #Hits (ColumnName, MatchCount)
 SELECT N''' + REPLACE(@Col, '''', '''''') + N''',
     COUNT(*)
 FROM ' + @FullTable + N'
 WHERE ' + QUOTENAME(@Col) + N' = @p
   AND ' + @RowFilter + N';

 INSERT INTO #Samples
 SELECT TOP (5)
     N''' + REPLACE(@Col, '''', '''''') + N''',
     t.*
 FROM ' + @FullTable + N' AS t
 WHERE ' + QUOTENAME(@Col) + N' = @p
AND ' + @RowFilter + N';
END';

        EXEC sp_executesql @sql, N'@p NVARCHAR(200)', @p = @SearchValue;

        FETCH NEXT FROM col_cur INTO @Col;
    END

    CLOSE col_cur;
    DEALLOCATE col_cur;
    SELECT ColumnName, MatchCount
    FROM   #Hits
    ORDER BY ColumnName;

SELECT *
FROM   #Samples
ORDER BY ColumnName;

    SELECT
        TargetTable = @FullTable,
        RowFilter   = @RowFilter,
        SearchValue = @SearchValue,
        ColumnsScanned = (SELECT COUNT(*) FROM #Cols);
